version: 2.1

jobs:
  # Job one with a unique name
  with_fix:
    docker:
     - image: cimg/node:23.3
    resource_class: xlarge
    steps:
      - checkout
      - run: pnpm install
      - run: cp cache-dir-fixed.js node_modules/next/dist/server/cache-dir.js
      - run: pnpm build
      - run: pnpm build
      - run: pnpm build
      - run: pnpm build
      - run: pnpm build
  # Job two with a unique name
  without_fix:
    docker:
     - image: cimg/node:23.3
    resource_class: xlarge
    steps:
      - checkout
      - run: pnpm install
      - run: pnpm build
      - run: pnpm build
      - run: pnpm build
      - run: pnpm build
      - run: pnpm build

workflows:
  # Name of workflow
  cache_tests:
    # List of jobs that will run
    jobs:
      - with_fix
      - without_fix